# Generated by Django 4.1 on 2023-06-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inquiries", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquiry",
            options={"ordering": ("-modified_at",), "verbose_name_plural": "Inquiries"},
        ),
        migrations.AlterField(
            model_name="inquirymessage",
            name="approach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="inquiries.inquiry",
            ),
        ),
    ]
