# Generated by Django 4.1 on 2023-06-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0002_region_listing_category_listing_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="listing_images"),
        ),
    ]
