# Generated by Django 4.1 on 2023-06-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0003_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="is_sold",
            field=models.BooleanField(default="False"),
        ),
    ]
