# Generated by Django 4.1 on 2023-06-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0006_alter_listing_price_alter_listing_price_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="price_currency",
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(null=True),
        ),
    ]
