# Generated by Django 4.1 on 2023-06-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0007_remove_listing_price_currency_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
