# Generated by Django 4.1 on 2023-06-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listing", "0008_alter_listing_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.FloatField(default="0"),
        ),
    ]
